### ISSUE TITLE
QUESTION: What is the value of using Firehose with DynamoDb streams vs just writing directly to S3?

### ISSUE THREAD

**Issue by mdgbayly** [awslabs/lambda-streams-to-firehose#41]
We are looking into dynamodb backup solutions and have been looking into this lib.
Out of the box it looks great, however we have a requirement to deploy to Montreal which doesn't currently support Lambda or Firehose.

So this is probably a dumb question and shows I'm not really understanding the value of Firehose, but if you already have a scaled stream processing application (processing your Dynamo Streams) why would you write to Firehose rather than directly to a destination like S3.

I've been looking into the DynamoDB Streams Kinesis Adapter, and considering building a stream handler that takes the Dynamo change stream and writes it to Firehose (potentially in a different region!!!) which then writes it to S3 in the Montreal region.  (Obviously incurs extra transfer charges!)

But why would I do that if I'm already having to write the Kinesis Adapter application?  Why not just write directly to S3 from the adapter application?  But if that were true for a Kinesis Adapter application why wouldn't we just do that from a Lambda function too.

I can see how using Firehose gives you a level of generality enabling you to redirect easily to different destinations. But are there other scalability reasons why it still makes more sense to go through Firehose? 

Thanks for any insights.

**Comment by benoittgt** [comment]
Hello @mdgbayly 

> why would you write to Firehose rather than directly to a destination like S3

For me because it's the easiest way to write data to s3. And it let the client plug if wanted to s3, Redshift or ElasticSearch. Also their is a buffer system, encryption, nice log mechanism...

I'm using this lambda because my Kinesis streams can have multiple consumers and because I need to write data into Redshift.

In your case maybe try to evaluate the cost of data across regions against the cost of building your own lambda dynamodb_reader_to_s3. 
You should maybe ask also to AWS support. I'm never use a lot DynamoDB but I'm very surprised you can't do it easily without Firehose ([1](https://github.com/markitx/dynamo-backup-to-s3), [2](https://github.com/CU-CloudCollab/aws-examples/tree/master/lambda/dynamodb-backup), [3](https://aws.amazon.com/articles/28549), [4](http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-importexport-ddb-part2.html)).

Bye

**Comment by IanMeyers** [comment]
Firehose takes responsibility for:

- Buffering data for the configured time you select, or up to a target filesize
- Compression of data on s3
- Encryption with the key you specify, if provided

This means that your producers can run at their 'native' speed and let Firehose handle the backpressure.
